# armv8
FROM arm64v8/ubuntu:19.10

# Override sources.list
COPY sources.list /etc/apt/sources.list
COPY trusted.gpg /etc/apt/trusted.gpg
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y adduser  \
    adwaita-icon-theme  \
    alsa-utils  \
    apt-utils  \
    apt  \
    at-spi2-core  \
    attr  \
    base-files  \
    base-passwd  \
    bash  \
    bc  \
    binutils-aarch64-linux-gnu  \
    binutils-common  \
    binutils  \
    bison  \
    brightness-udev  \
    brightnessctl  \
    bsdutils  \
    build-essential  \
    busybox-initramfs  \
    bzip2  \
    ca-certificates  \
    cloud-guest-utils  \
    cmake-data  \
    cmake  \
    console-setup-linux  \
    console-setup  \
    coreutils  \
    cpio  \
    cpp-9  \
    cpp  \
    crda  \
    cron  \
    curl  \
    dash  \
    dbus-user-session  \
    dbus  \
    dconf-gsettings-backend  \
    dconf-service  \
    debconf-i18n  \
    debconf  \
    debianutils  \
    device-tree-compiler  \
    dh-python  \
    dialog  \
    diffutils  \
    dirmngr  \
    distro-info-data  \
    dmsetup  \
    dns-root-data  \
    dnsmasq-base  \
    dosfstools  \
    dpkg-dev  \
    dpkg  \
    e2fsprogs  \
    eject  \
    espeak-data  \
    espeak  \
    evemu-tools  \
    evtest  \
    exfat-utils  \
    fakeroot  \
    fatresize  \
    fdisk  \
    ffmpeg  \
    file  \
    findutils  \
    flex  \
    fluid-soundfont-gm  \
    fluidsynth  \
    fontconfig-config  \
    fontconfig  \
    fonts-dejavu-core  \
    fonts-droid-fallback  \
    fonts-noto-cjk  \
    fonts-noto-mono  \
    freeglut3  \
    fuse  \
    g++-9  \
    g++  \
    gcc-9-base  \
    gcc-9  \
    gcc  \
    gir1.2-glib-2.0  \
    gir1.2-ibus-1.0  \
    git-man  \
    git  \
    glib-networking-common  \
    glib-networking-services  \
    glib-networking  \
    gnupg-l10n  \
    gnupg-utils  \
    gnupg2  \
    gnupg  \
    gpg-agent  \
    gpg-wks-client  \
    gpg-wks-server  \
    gpg  \
    gpgconf  \
    gpgsm  \
    gpgv  \
    grep  \
    gsettings-desktop-schemas  \
    gtk-update-icon-cache  \
    gzip  \
    hicolor-icon-theme  \
    hostname  \
    humanity-icon-theme  \
    ibverbs-providers  \
    init-system-helpers  \
    init  \
    initramfs-tools-bin  \
    initramfs-tools-core  \
    initramfs-tools  \
    inotify-tools  \
    iproute2  \
    iptables  \
    iputils-ping  \
    isc-dhcp-client  \
    isc-dhcp-common  \
    iw  \
    kbd  \
    keyboard-configuration  \
    klibc-utils  \
    kmod  \
    krb5-locales  \
    less  \
    liba52-0.7.4  \
    libaacs0  \
    libacl1  \
    libalgorithm-diff-perl  \
    libalgorithm-diff-xs-perl  \
    libalgorithm-merge-perl  \
    libaom0  \
    libapparmor1  \
    libapt-pkg5.90  \
    libarchive-zip-perl  \
    libarchive13  \
    libargon2-1  \
    libaribb24-0  \
    libasan5  \
    libasn1-8-heimdal  \
    libasound2-data  \
    libasound2-dev  \
    libasound2  \
    libass9  \
    libassuan0  \
    libasyncns0  \
    libatk-bridge2.0-0  \
    libatk1.0-0  \
    libatk1.0-data  \
    libatm1  \
    libatomic1  \
    libatspi2.0-0  \
    libattr1  \
    libaudit-common  \
    libaudit1  \
    libauthen-sasl-perl  \
    libavahi-client3  \
    libavahi-common-data  \
    libavahi-common3  \
    libavc1394-0  \
    libavcodec58  \
    libavdevice58  \
    libavfilter7  \
    libavformat58  \
    libavresample4  \
    libavutil56  \
    libbasicusageenvironment1  \
    libbdplus0  \
    libbinutils  \
    libblkid-dev  \
    libblkid1  \
    libbluetooth3  \
    libbluray2  \
    libboost-date-time1.67.0  \
    libboost-filesystem1.67.0  \
    libboost-iostreams1.67.0  \
    libboost-locale1.67.0  \
    libboost-serialization1.67.0  \
    libboost-system1.67.0  \
    libboost-thread1.67.0  \
    libbrotli1  \
    libbs2b0  \
    libbsd0  \
    libbz2-1.0  \
    libc-bin  \
    libc-dev-bin  \
    libc6-dev  \
    libc6  \
    libcaca0  \
    libcairo-gobject2  \
    libcairo2  \
    libcap-ng0  \
    libcap2-bin  \
    libcap2  \
    libcapnp-0.7.0  \
    libcc1-0  \
    libcddb2  \
    libcdio-cdda2  \
    libcdio-paranoia2  \
    libcdio18  \
    libcephfs2  \
    libchromaprint1  \
    libcodec2-0.8.1  \
    libcolord2  \
    libcom-err2  \
    libcroco3  \
    libcryptsetup12  \
    libcups2  \
    libcurl3-gnutls  \
    libcurl4-openssl-dev  \
    libcurl4  \
    libdata-dump-perl  \
    libdatrie1  \
    libdb5.3  \
    libdbus-1-3  \
    libdbus-1-dev  \
    libdc1394-22  \
    libdca0  \
    libdconf1  \
    libdebconfclient0  \
    libdevmapper1.02.1  \
    libdns-export1104  \
    libdouble-conversion3  \
    libdpkg-perl  \
    libdrm-amdgpu1  \
    libdrm-common  \
    libdrm-dev  \
    libdrm-etnaviv1  \
    libdrm-freedreno1  \
    libdrm-nouveau2  \
    libdrm-radeon1  \
    libdrm-tegra0  \
    libdrm2  \
    libdvbpsi10  \
    libdvdnav4  \
    libdvdread4  \
    libebml4v5  \
    libedit2  \
    libegl-mesa0  \
    libegl1-mesa-dev  \
    libegl1  \
    libeigen3-dev  \
    libelf1  \
    libencode-locale-perl  \
    libepoxy0  \
    liberror-perl  \
    libespeak1  \
    libestr0  \
    libevdev2  \
    libevemu3  \
    libexpat1-dev  \
    libexpat1  \
    libext2fs2  \
    libfaad2  \
    libfakeroot  \
    libfastjson4  \
    libfdisk1  \
    libffi-dev  \
    libffi6  \
    libfftw3-double3  \
    libfftw3-single3  \
    libfile-basedir-perl  \
    libfile-desktopentry-perl  \
    libfile-fcntllock-perl  \
    libfile-listing-perl  \
    libfile-mimeinfo-perl  \
    libfl-dev  \
    libfl2  \
    libflac8  \
    libflite1  \
    libfluidsynth1  \
    libfont-afm-perl  \
    libfontconfig1  \
    libfontenc1  \
    libfreeimage-dev  \
    libfreeimage3  \
    libfreetype6  \
    libfribidi0  \
    libfuse2  \
    libgbm1  \
    libgcc-9-dev  \
    libgcc1  \
    libgcrypt20  \
    libgdbm-compat4  \
    libgdbm6  \
    libgdk-pixbuf2.0-0  \
    libgdk-pixbuf2.0-bin  \
    libgdk-pixbuf2.0-common  \
    libgirepository-1.0-1  \
    libgl1-mesa-dev  \
    libgl1-mesa-dri  \
    libgl1  \
    libglapi-mesa  \
    libgles1  \
    libgles2-mesa-dev  \
    libgles2  \
    libglib2.0-0  \
    libglib2.0-bin  \
    libglib2.0-data  \
    libglib2.0-dev-bin  \
    libglib2.0-dev  \
    libglu1-mesa-dev  \
    libglu1-mesa  \
    libglvnd-core-dev  \
    libglvnd-dev  \
    libglvnd0  \
    libglx-mesa0  \
    libglx0  \
    libgme0  \
    libgmp10  \
    libgnutls30  \
    libgomp1  \
    libgpg-error-l10n  \
    libgpg-error0  \
    libgpgme11  \
    libgpm2  \
    libgraphite2-3  \
    libgroupsock8  \
    libgsm1  \
    libgssapi-krb5-2  \
    libgssapi3-heimdal  \
    libgtk-3-0  \
    libgtk-3-bin  \
    libgtk-3-common  \
    libgudev-1.0-0  \
    libharfbuzz0b  \
    libhcrypto4-heimdal  \
    libheimbase1-heimdal  \
    libheimntlm0-heimdal  \
    libhogweed4  \
    libhtml-form-perl  \
    libhtml-format-perl  \
    libhtml-parser-perl  \
    libhtml-tagset-perl  \
    libhtml-tree-perl  \
    libhttp-cookies-perl  \
    libhttp-daemon-perl  \
    libhttp-date-perl  \
    libhttp-message-perl  \
    libhttp-negotiate-perl  \
    libhx509-5-heimdal  \
    libibus-1.0-5  \
    libibus-1.0-dev  \
    libibverbs1  \
    libice-dev  \
    libice6  \
    libicu63  \
    libidn11  \
    libidn2-0  \
    libiec61883-0  \
    libilmbase23  \
    libinotifytools0  \
    libinput-bin  \
    libinput10  \
    libio-html-perl  \
    libio-socket-ssl-perl  \
    libio-stringy-perl  \
    libip4tc2  \
    libip6tc2  \
    libipc-system-simple-perl  \
    libiptc0  \
    libisc-export1100  \
    libisl21  \
    libitm1  \
    libixml10  \
    libjack-jackd2-0  \
    libjansson4  \
    libjbig0  \
    libjpeg-turbo8  \
    libjpeg8  \
    libjson-c4  \
    libjson-glib-1.0-0  \
    libjson-glib-1.0-common  \
    libjsoncpp1  \
    libjxr0  \
    libk5crypto3  \
    libkate1  \
    libkeyutils1  \
    libklibc  \
    libkmod2  \
    libkrb5-26-heimdal  \
    libkrb5-3  \
    libkrb5support0  \
    libksba8  \
    liblcms2-2  \
    libldap-2.4-2  \
    libldap-common  \
    libldb1  \
    liblilv-0-0  \
    liblirc-client0  \
    liblivemedia64  \
    libllvm9  \
    liblocale-gettext-perl  \
    liblsan0  \
    liblua5.2-0  \
    liblwp-mediatypes-perl  \
    liblwp-protocol-https-perl  \
    liblz4-1  \
    liblzma5  \
    libmad0  \
    libmagic-mgc  \
    libmagic1  \
    libmailtools-perl  \
    libmatroska6v5  \
    libmbim-glib4  \
    libmbim-proxy  \
    libmicrodns0  \
    libminizip1  \
    libmirclient-dev  \
    libmirclient9  \
    libmircommon-dev  \
    libmircommon7  \
    libmircookie-dev  \
    libmircookie2  \
    libmircore-dev  \
    libmircore1  \
    libmirprotobuf3  \
    libmm-glib0  \
    libmnl0  \
    libmodplug1  \
    libmount-dev  \
    libmount1  \
    libmp3lame0  \
    libmpc3  \
    libmpcdec6  \
    libmpdec2  \
    libmpeg2-4  \
    libmpfr6  \
    libmpg123-0  \
    libmtdev1  \
    libmtp-common  \
    libmtp-runtime  \
    libmtp9  \
    libmysofa0  \
    libncurses6  \
    libncursesw6  \
    libndp0  \
    libnet-dbus-perl  \
    libnet-http-perl  \
    libnet-smtp-ssl-perl  \
    libnet-ssleay-perl  \
    libnetfilter-conntrack3  \
    libnettle6  \
    libnewt0.52  \
    libnfnetlink0  \
    libnfs12  \
    libnftnl11  \
    libnghttp2-14  \
    libnl-3-200  \
    libnl-genl-3-200  \
    libnl-route-3-200  \
    libnm0  \
    libnorm1  \
    libnpth0  \
    libnspr4  \
    libnss-systemd  \
    libnss3  \
    libntfs-3g883  \
    libnuma1  \
    libogg0  \
    libopenal-data  \
    libopenal1  \
    libopenexr23  \
    libopengl0  \
    libopenjp2-7  \
    libopenmpt-modplug1  \
    libopenmpt0  \
    libopus0  \
    libopusfile0  \
    libp11-kit0  \
    libpam-cap  \
    libpam-modules-bin  \
    libpam-modules  \
    libpam-runtime  \
    libpam-systemd  \
    libpam0g  \
    libpango-1.0-0  \
    libpangocairo-1.0-0  \
    libpangoft2-1.0-0  \
    libparted-fs-resize0  \
    libparted2  \
    libpcap0.8  \
    libpcre16-3  \
    libpcre2-16-0  \
    libpcre2-32-0  \
    libpcre2-8-0  \
    libpcre2-dev  \
    libpcre2-posix0  \
    libpcre3-dev  \
    libpcre32-3  \
    libpcre3  \
    libpcrecpp0v5  \
    libpcsclite1  \
    libperl5.28  \
    libpgm-5.2-0  \
    libpipeline1  \
    libpixman-1-0  \
    libplymouth4  \
    libpng-tools  \
    libpng16-16  \
    libpolkit-agent-1-0  \
    libpolkit-gobject-1-0  \
    libpopt0  \
    libportaudio2  \
    libpostproc55  \
    libprocps7  \
    libprotobuf-dev  \
    libprotobuf-lite17  \
    libprotobuf17  \
    libproxy-tools  \
    libproxy1v5  \
    libpsl5  \
    libpthread-stubs0-dev  \
    libpulse-dev  \
    libpulse-mainloop-glib0  \
    libpulse0  \
    libpython-stdlib  \
    libpython2-stdlib  \
    libpython2.7-minimal  \
    libpython2.7-stdlib  \
    libpython3-dev  \
    libpython3-stdlib  \
    libpython3.7-dev  \
    libpython3.7-minimal  \
    libpython3.7-stdlib  \
    libpython3.7  \
    libqmi-glib5  \
    libqmi-proxy  \
    libqt5core5a  \
    libqt5dbus5  \
    libqt5gui5  \
    libqt5network5  \
    libqt5svg5  \
    libqt5widgets5  \
    libqt5x11extras5  \
    librados2  \
    libraw1394-11  \
    libraw19  \
    librdmacm1  \
    libreadline8  \
    libresid-builder0c2a  \
    librest-0.7-0  \
    librhash0  \
    libroken18-heimdal  \
    librsvg2-2  \
    librsvg2-common  \
    librtmp1  \
    librubberband2  \
    libsamplerate0  \
    libsasl2-2  \
    libsasl2-modules-db  \
    libsasl2-modules  \
    libsdl-image1.2  \
    libsdl1.2debian  \
    libsdl2-2.0-0  \
    libsdl2-dev  \
    libsdl2-mixer-2.0-0  \
    libsdl2-mixer-dev  \
    libsdl2-net-2.0-0  \
    libsdl2-ttf-2.0-0  \
    libsdl2-ttf-dev  \
    libseccomp2  \
    libsecret-1-0  \
    libsecret-common  \
    libselinux1-dev  \
    libselinux1  \
    libsemanage-common  \
    libsemanage1  \
    libsensors-config  \
    libsensors5  \
    libsepol1-dev  \
    libsepol1  \
    libserd-0-0  \
    libshine3  \
    libshout3  \
    libsidplay2  \
    libsigsegv2  \
    libslang2  \
    libsm-dev  \
    libsm6  \
    libsmartcols1  \
    libsnappy1v5  \
    libsndfile1  \
    libsndio-dev  \
    libsndio7.0  \
    libsodium23  \
    libsonic0  \
    libsord-0-0  \
    libsoup-gnome2.4-1  \
    libsoup2.4-1  \
    libsoxr0  \
    libspatialaudio0  \
    libspeex1  \
    libspeexdsp1  \
    libsqlite3-0  \
    libsratom-0-0  \
    libss2  \
    libssh-4  \
    libssh-gcrypt-4  \
    libssh2-1  \
    libssl-dev  \
    libssl1.1  \
    libstdc++-9-dev  \
    libstdc++6  \
    libswresample3  \
    libswscale5  \
    libsystemd0  \
    libtag1v5-vanilla  \
    libtag1v5  \
    libtalloc2  \
    libtasn1-6  \
    libtdb1  \
    libteamdctl0  \
    libtevent0  \
    libtext-charwidth-perl  \
    libtext-iconv-perl  \
    libtext-wrapi18n-perl  \
    libthai-data  \
    libthai0  \
    libtheora0  \
    libtie-ixhash-perl  \
    libtiff5  \
    libtimedate-perl  \
    libtinfo6  \
    libtry-tiny-perl  \
    libtsan0  \
    libtwolame0  \
    libubsan1  \
    libudev-dev  \
    libudev1  \
    libunistring2  \
    libupnp13  \
    liburi-perl  \
    libusageenvironment3  \
    libusb-1.0-0  \
    libutempter0  \
    libuuid1  \
    libuv1  \
    libv4l-0  \
    libv4l-dev  \
    libv4l2rds0  \
    libv4lconvert0  \
    libva-drm2  \
    libva-x11-2  \
    libva2  \
    libvdpau1  \
    libvidstab1.1  \
    libvlc-bin  \
    libvlc5  \
    libvlccore9  \
    libvorbis0a  \
    libvorbisenc2  \
    libvorbisfile3  \
    libvpx6  \
    libwacom-bin  \
    libwacom-common  \
    libwacom2  \
    libwavpack1  \
    libwayland-bin  \
    libwayland-client0  \
    libwayland-cursor0  \
    libwayland-dev  \
    libwayland-egl1  \
    libwayland-server0  \
    libwbclient0  \
    libwebp6  \
    libwebpmux3  \
    libwind0-heimdal  \
    libwrap0  \
    libwww-perl  \
    libwww-robotrules-perl  \
    libx11-6  \
    libx11-data  \
    libx11-dev  \
    libx11-protocol-perl  \
    libx11-xcb-dev  \
    libx11-xcb1  \
    libx264-155  \
    libx265-176  \
    libxau-dev  \
    libxau6  \
    libxaw7  \
    libxcb-dri2-0-dev  \
    libxcb-dri2-0  \
    libxcb-dri3-0  \
    libxcb-dri3-dev  \
    libxcb-glx0-dev  \
    libxcb-glx0  \
    libxcb-icccm4  \
    libxcb-image0  \
    libxcb-keysyms1  \
    libxcb-present-dev  \
    libxcb-present0  \
    libxcb-randr0-dev  \
    libxcb-randr0  \
    libxcb-render-util0  \
    libxcb-render0-dev  \
    libxcb-render0  \
    libxcb-shape0-dev  \
    libxcb-shape0  \
    libxcb-shm0  \
    libxcb-sync-dev  \
    libxcb-sync1  \
    libxcb-util1  \
    libxcb-xfixes0-dev  \
    libxcb-xfixes0  \
    libxcb-xinerama0  \
    libxcb-xinput0  \
    libxcb-xkb1  \
    libxcb1-dev  \
    libxcb1  \
    libxcomposite1  \
    libxcursor-dev  \
    libxcursor1  \
    libxdamage-dev  \
    libxdamage1  \
    libxdmcp-dev  \
    libxdmcp6  \
    libxext-dev  \
    libxext6  \
    libxfixes-dev  \
    libxfixes3  \
    libxft2  \
    libxi-dev  \
    libxi6  \
    libxinerama-dev  \
    libxinerama1  \
    libxkbcommon-dev  \
    libxkbcommon-x11-0  \
    libxkbcommon0  \
    libxml-parser-perl  \
    libxml-twig-perl  \
    libxml-xpathengine-perl  \
    libxml2  \
    libxmu6  \
    libxmuu1  \
    libxpm4  \
    libxrandr-dev  \
    libxrandr2  \
    libxrender-dev  \
    libxrender1  \
    libxshmfence-dev  \
    libxshmfence1  \
    libxss-dev  \
    libxss1  \
    libxt-dev  \
    libxt6  \
    libxtables12  \
    libxtst6  \
    libxv-dev  \
    libxv1  \
    libxvidcore4  \
    libxxf86dga1  \
    libxxf86vm-dev  \
    libxxf86vm1  \
    libyaml-0-2  \
    libzmq5  \
    libzstd1  \
    libzvbi-common  \
    libzvbi0  \
    linux-base  \
    linux-libc-dev  \
    locales  \
    logrotate  \
    logsave  \
    lsb-base  \
    lsb-release  \
    lz4  \
    m4  \
    make  \
    manpages-dev  \
    manpages  \
    mawk  \
    mesa-common-dev  \
    mesa-va-drivers  \
    mesa-vdpau-drivers  \
    mime-support  \
    modemmanager  \
    mount  \
    nano  \
    ncurses-base  \
    ncurses-bin  \
    ncurses-term  \
    net-tools  \
    netbase  \
    netcat-openbsd  \
    netplan.io  \
    network-manager-pptp  \
    network-manager  \
    networkd-dispatcher  \
    ntfs-3g  \
    openssh-client  \
    openssh-server  \
    openssh-sftp-server  \
    openssl  \
    passwd  \
    patch  \
    perl-base  \
    perl-modules-5.28  \
    perl-openssl-defaults  \
    perl  \
    pinentry-curses  \
    pkg-config  \
    plymouth-theme-ubuntu-text  \
    plymouth  \
    policykit-1  \
    ppp  \
    pptp-linux  \
    procps  \
    psmisc  \
    publicsuffix  \
    python-minimal  \
    python-pip-whl  \
    python2-minimal  \
    python2.7-minimal  \
    python2.7  \
    python2  \
    python3-asn1crypto  \
    python3-certifi  \
    python3-cffi-backend  \
    python3-chardet  \
    python3-crypto  \
    python3-cryptography  \
    python3-dbus  \
    python3-dev  \
    python3-distutils  \
    python3-dnspython  \
    python3-entrypoints  \
    python3-evdev  \
    python3-gi  \
    python3-idna  \
    python3-keyring  \
    python3-keyrings.alt  \
    python3-ldb  \
    python3-lib2to3  \
    python3-libevdev  \
    python3-minimal  \
    python3-nacl  \
    python3-netifaces  \
    python3-pip  \
    python3-pkg-resources  \
    python3-pymacaroons  \
    python3-requests  \
    python3-samba  \
    python3-secretstorage  \
    python3-setuptools  \
    python3-six  \
    python3-talloc  \
    python3-tdb  \
    python3-urllib3  \
    python3-wheel  \
    python3-xdg  \
    python3-yaml  \
    python3.7-dev  \
    python3.7-minimal  \
    python3.7  \
    python3  \
    python  \
    qsynth  \
    qt5-gtk-platformtheme  \
    qttranslations5-l10n  \
    readline-common  \
    rfkill  \
    rsync  \
    rsyslog  \
    samba-common-bin  \
    samba-common  \
    samba-dsdb-modules  \
    samba-libs  \
    samba-vfs-modules  \
    samba  \
    screen  \
    sed  \
    sensible-utils  \
    shared-mime-info  \
    ssh-import-id  \
    sudo  \
    systemd-sysv  \
    systemd  \
    sysvinit-utils  \
    tar  \
    tdb-tools  \
    timgm6mb-soundfont  \
    tzdata  \
    u-boot-tools  \
    uboot  \
    ubuntu-advantage-tools  \
    ubuntu-keyring  \
    ubuntu-minimal  \
    ubuntu-mono  \
    ucf  \
    udev  \
    unzip  \
    usb-modeswitch-data  \
    usb-modeswitch  \
    util-linux  \
    uuid-dev  \
    uuid-runtime  \
    va-driver-all  \
    vdpau-driver-all  \
    vim-common  \
    vim-tiny  \
    vlc-data  \
    vlc-plugin-base  \
    wget  \
    whiptail  \
    wireless-regdb  \
    wpasupplicant  \
    x11-common  \
    x11-utils  \
    x11-xserver-utils  \
    x11proto-core-dev  \
    x11proto-damage-dev  \
    x11proto-dev  \
    x11proto-fixes-dev  \
    x11proto-input-dev  \
    x11proto-randr-dev  \
    x11proto-scrnsaver-dev  \
    x11proto-xext-dev  \
    x11proto-xf86vidmode-dev  \
    x11proto-xinerama-dev  \
    xauth  \
    xdg-user-dirs  \
    xdg-utils  \
    xkb-data  \
    xorg-sgml-doctools  \
    xtrans-dev  \
    xxd  \
    xz-utils  \
    zip  \
    zlib1g-dev  \
    zlib1g

ENTRYPOINT ["/bin/bash"]
